2023-03-10 05:13:37,013 ERROR: Exception on /login [GET] [in d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\School\Bezig\cloud\microblog\app\routes.py", line 76, in login
    return render_template('login.html', title=_('Sign In'), form=form)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\base.html", line 58, in template
    $(destElem).html('<img src="{{ url_for(',static, 'filename'=loading.gif,') }}">');
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'filename'
2023-03-10 05:13:41,007 ERROR: Exception on /login [GET] [in d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\School\Bezig\cloud\microblog\app\routes.py", line 76, in login
    return render_template('login.html', title=_('Sign In'), form=form)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\base.html", line 58, in template
    $(destElem).html('<img src="{{ url_for(',static, 'filename'=loading.gif,') }}">');
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'filename'
2023-03-10 05:13:41,604 ERROR: Exception on /login [GET] [in d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\School\Bezig\cloud\microblog\app\routes.py", line 76, in login
    return render_template('login.html', title=_('Sign In'), form=form)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\base.html", line 58, in template
    $(destElem).html('<img src="{{ url_for(',static, 'filename'=loading.gif,') }}">');
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'filename'
2023-03-10 05:13:41,986 ERROR: Exception on /login [GET] [in d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\School\Bezig\cloud\microblog\app\routes.py", line 76, in login
    return render_template('login.html', title=_('Sign In'), form=form)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\base.html", line 58, in template
    $(destElem).html('<img src="{{ url_for(',static, 'filename'=loading.gif,') }}">');
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'filename'
