2023-03-10 05:51:03,398 ERROR: Exception on / [GET] [in d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\School\Bezig\cloud\microblog\app\main\routes.py", line 46, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\School\Bezig\cloud\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\School\Bezig\cloud\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "D:\School\Bezig\cloud\microblog\app\templates\base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "d:\School\Bezig\cloud\microblog\.venv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2023-03-10 05:59:50,246 INFO: Microblog startup [in D:\School\Bezig\cloud\microblog\app\__init__.py:52]
2023-03-10 06:44:08,082 INFO: Microblog startup [in D:\School\Bezig\cloud\microblog\app\__init__.py:52]
